// Web app manifest — makes the brand mark the home-screen icon on Android and
// the window icon for an installed PWA. Icons are generated by
// scripts/generate-brand-assets.ts; colors match app/globals.css tokens.
import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'learn.kuray.dev — Engineer Roadmap',
    short_name: 'learn.kuray',
    description: 'Path to the software business era.',
    start_url: '/',
    display: 'standalone',
    background_color: '#0f172a',
    theme_color: '#3b82f6',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
