// Two ways to fit 500 readings into 50 pixels of chart, and what each one
// does to the thing you were looking for.
//
// Determinism: the series is generated by fixed arithmetic, both algorithms
// are pure, and rounding is fixed. No clock, no random, no library.

const N = 500;
const TARGET = 50;

// A plausible slow signal — a daily cycle with a slow drift — plus two short
// excursions of the kind an alert exists to catch. Everything is a fixed
// function of the index, so the series is identical on every run.
function series() {
  const points = [];
  for (let i = 0; i < N; i++) {
    let v = 20 + 3 * Math.sin((i / N) * 4 * Math.PI) + i * 0.004;
    // A sharp spike over four samples.
    if (i >= 187 && i <= 190) v += 9.5;
    // A single-sample dropout.
    if (i === 322) v -= 7.2;
    points.push({ x: i, y: Math.round(v * 1000) / 1000 });
  }
  return points;
}

/** Largest Triangle Three Buckets (Steinarsson, 2013). Keeps the first and
 *  last points, splits the rest into `target - 2` buckets, and from each
 *  bucket takes the point forming the largest triangle with the previously
 *  kept point and the mean of the next bucket. */
function lttb(data, target) {
  if (target >= data.length || target < 3) return data;
  const bucketSize = (data.length - 2) / (target - 2);
  const out = [data[0]];
  let a = 0;

  for (let i = 0; i < target - 2; i++) {
    // Mean of the NEXT bucket — the third corner of the triangle.
    const nextStart = Math.floor((i + 1) * bucketSize) + 1;
    const nextEnd = Math.min(Math.floor((i + 2) * bucketSize) + 1, data.length);
    let avgX = 0;
    let avgY = 0;
    for (let j = nextStart; j < nextEnd; j++) {
      avgX += data[j].x;
      avgY += data[j].y;
    }
    const count = nextEnd - nextStart;
    avgX /= count;
    avgY /= count;

    const start = Math.floor(i * bucketSize) + 1;
    const end = Math.floor((i + 1) * bucketSize) + 1;
    let best = start;
    let bestArea = -1;
    for (let j = start; j < end; j++) {
      const area = Math.abs(
        (data[a].x - avgX) * (data[j].y - data[a].y) - (data[a].x - data[j].x) * (avgY - data[a].y)
      );
      if (area > bestArea) {
        bestArea = area;
        best = j;
      }
    }
    out.push(data[best]);
    a = best;
  }

  out.push(data[data.length - 1]);
  return out;
}

/** The obvious alternative: split into buckets and take each bucket's mean. */
function bucketAverage(data, target) {
  const size = Math.ceil(data.length / target);
  const out = [];
  for (let i = 0; i < data.length; i += size) {
    const bucket = data.slice(i, i + size);
    out.push({
      x: bucket.reduce((s, p) => s + p.x, 0) / bucket.length,
      y: Math.round((bucket.reduce((s, p) => s + p.y, 0) / bucket.length) * 1000) / 1000,
    });
  }
  return out;
}

const data = series();
const extent = (points) => ({
  min: Math.min(...points.map((p) => p.y)),
  max: Math.max(...points.map((p) => p.y)),
});

const full = extent(data);
const byLttb = lttb(data, TARGET);
const byAverage = bucketAverage(data, TARGET);

console.log(`${N} points down to about ${TARGET}`);
console.log('');
console.log('                 points   minimum   maximum    range kept');
for (const [name, points] of [['original', data], ['LTTB', byLttb], ['bucket average', byAverage]]) {
  const e = extent(points);
  const kept = ((e.max - e.min) / (full.max - full.min)) * 100;
  console.log(
    `  ${name.padEnd(15)} ${String(points.length).padStart(4)}   ${e.min.toFixed(3).padStart(7)}   ` +
      `${e.max.toFixed(3).padStart(7)}   ${kept.toFixed(1).padStart(9)}%`
  );
}
console.log('');

// The two features that matter, checked by name rather than by eye.
const SPIKE_FROM = 187;
const SPIKE_TO = 190;
const SPIKE_TOP = Math.max(...data.filter((p) => p.x >= SPIKE_FROM && p.x <= SPIKE_TO).map((p) => p.y));
const DROPOUT_X = 322;
const DROPOUT = data.find((p) => p.x === DROPOUT_X).y;

/** The honest question is not whether the exact peak SAMPLE survived, but
 *  whether the excursion is still visible — and how much of its height is
 *  left. A summary that reports 90% of a spike has told you it happened. */
function peakKept(points, from, to) {
  const inside = points.filter((p) => p.x >= from - 1 && p.x <= to + 1);
  return inside.length === 0 ? null : Math.max(...inside.map((p) => p.y));
}

const baseline = 20 + 3 * Math.sin((SPIKE_FROM / N) * 4 * Math.PI) + SPIKE_FROM * 0.004;
const height = (peak) => (peak === null ? 0 : ((peak - baseline) / (SPIKE_TOP - baseline)) * 100);

console.log(`the four-sample spike, peaking at y = ${SPIKE_TOP.toFixed(3)} over a baseline of ${baseline.toFixed(3)}:`);
for (const [name, points] of [['LTTB', byLttb], ['bucket average', byAverage]]) {
  const peak = peakKept(points, SPIKE_FROM, SPIKE_TO);
  console.log(
    `  ${name.padEnd(15)} highest point kept there: ${peak === null ? 'none' : peak.toFixed(3)}` +
      `   ${height(peak).toFixed(1)}% of the excursion`
  );
}
console.log('');

console.log(`the single-sample dropout at y = ${DROPOUT.toFixed(3)}:`);
for (const [name, points] of [['LTTB', byLttb], ['bucket average', byAverage]]) {
  const inside = points.filter((p) => p.x >= DROPOUT_X - 5 && p.x <= DROPOUT_X + 5);
  const low = inside.length === 0 ? null : Math.min(...inside.map((p) => p.y));
  console.log(`  ${name.padEnd(15)} lowest point kept there: ${low === null ? 'none' : low.toFixed(3)}`);
}
console.log('');
console.log('Neither result is a lie about the data it reports. The average really is the');
console.log('average. What it is wrong about is the QUESTION the chart is being asked, which');
console.log('is almost always "did anything unusual happen" rather than "what was the mean".');
console.log('');
console.log('LTTB keeps the shape and does NOT keep the arithmetic: the mean of its output is');
console.log(`${(byLttb.reduce((s, p) => s + p.y, 0) / byLttb.length).toFixed(3)} against the original's ${(data.reduce((s, p) => s + p.y, 0) / data.length).toFixed(3)}. Use it to draw, never to compute.`);
