// What a clash run actually costs, and what a tolerance actually changes.
// Counted on a fixed model, not estimated from a project nobody can inspect.
//
// The model below is generated by arithmetic, not by random numbers: three
// discipline sets of axis-aligned boxes laid out on a grid, with deliberate
// interferences produced by fixed offsets. Every count this script prints is
// therefore reproducible byte for byte.
//
// Three questions get answered:
//   1. how many pairs a brute-force check would examine
//   2. how many survive an axis-aligned bounding-box (broad phase) test
//   3. how the clash count moves as the tolerance moves
//
// No geometry is drawn, no mesh is intersected, and no library is used. A
// broad phase is an interval-overlap query on three axes; the narrow phase
// here is a decision rule over the overlap depth. Both are arithmetic.
//
// Determinism: fixed element table, fixed tolerance list, integer millimetres,
// sorted output. No clock, no random.

/** Boxes in millimetres: [xmin, ymin, zmin, xmax, ymax, zmax].
 *
 *  The interferences are graded on purpose. Each duct is dropped so that it
 *  penetrates the beam zone by a specific depth, and each riser is offset so
 *  that it clips a beam by a specific width. Those depths are what the
 *  tolerance sweep below is measured against -- a model whose every
 *  interference is 200 mm deep cannot show what a tolerance does. */
const BEAM_Z_BOTTOM = 3000;
const BEAM_Z_TOP = 3600;

// Penetration depth (mm) of each duct into the beam zone, from below.
const DUCT_PENETRATION = [2, 4, 8, 15, 22, 30, 45, 60, 120, 240];
// Width (mm) by which each riser clips the beam it passes.
const RISER_CLIP = [3, 6, 12, 28, 40, 75, 150, 260];

function makeModel() {
  const els = [];
  // Structure: 12 beams every 3 m along x, spanning y, in a fixed z band.
  for (let i = 0; i < 12; i++) {
    const x = i * 3000;
    els.push({ id: `STR-${i}`, discipline: 'structure', box: [x, 0, BEAM_Z_BOTTOM, x + 300, 12000, BEAM_Z_TOP] });
  }
  // HVAC: duct runs along x, each raised into the beam zone by its own depth.
  for (let i = 0; i < DUCT_PENETRATION.length; i++) {
    const y = i * 1200;
    const top = BEAM_Z_BOTTOM + DUCT_PENETRATION[i];
    els.push({ id: `HVA-${i}`, discipline: 'hvac', box: [0, y, top - 400, 33000, y + 600, top] });
  }
  // Plumbing: full-height risers, each clipping the near edge of one beam.
  for (let i = 0; i < RISER_CLIP.length; i++) {
    const beamX = (i + 1) * 3000; // the beam this riser sits against
    const x = beamX - 200 + RISER_CLIP[i]; // overlap on x is exactly the clip
    const y = 900 + i * 1300;
    els.push({ id: `PLU-${i}`, discipline: 'plumbing', box: [x, y, 0, x + 200, y + 200, 6000] });
  }
  return els;
}

const overlap1d = (aMin, aMax, bMin, bMax) => Math.min(aMax, bMax) - Math.max(aMin, bMin);

/** Broad phase: do the two boxes overlap on all three axes at all? */
function boxesOverlap(a, b) {
  return (
    overlap1d(a[0], a[3], b[0], b[3]) > 0 &&
    overlap1d(a[1], a[4], b[1], b[4]) > 0 &&
    overlap1d(a[2], a[5], b[2], b[5]) > 0
  );
}

/** Narrow phase, for axis-aligned boxes: the smallest overlap across the three
 *  axes is how far one would have to move to separate them -- the penetration
 *  depth the tolerance is compared against. */
function penetration(a, b) {
  return Math.min(
    overlap1d(a[0], a[3], b[0], b[3]),
    overlap1d(a[1], a[4], b[1], b[4]),
    overlap1d(a[2], a[5], b[2], b[5])
  );
}

const els = makeModel();
const n = els.length;
const brute = (n * (n - 1)) / 2;

const candidates = [];
for (let i = 0; i < n; i++) {
  for (let j = i + 1; j < n; j++) {
    if (els[i].discipline === els[j].discipline) continue; // same-discipline pairs are not coordination
    if (boxesOverlap(els[i].box, els[j].box)) candidates.push([els[i], els[j]]);
  }
}

console.log(`model: ${n} elements (${els.filter((e) => e.discipline === 'structure').length} structure, ` +
  `${els.filter((e) => e.discipline === 'hvac').length} hvac, ${els.filter((e) => e.discipline === 'plumbing').length} plumbing)`);
console.log('');
console.log(`pairs a brute-force narrow-phase check would examine : ${brute}`);
console.log(`pairs left after dropping same-discipline pairs      : ${
  (() => { let c = 0; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) if (els[i].discipline !== els[j].discipline) c++; return c; })()
}`);
console.log(`pairs left after the axis-aligned broad phase        : ${candidates.length}`);
console.log(`fraction of pairs the broad phase removed            : ${
  (((brute - candidates.length) / brute) * 100).toFixed(1)}%`);
console.log('');

console.log('clash count as the tolerance moves (penetration must exceed the tolerance):');
console.log('  tolerance   clashes   by discipline pair');
for (const tol of [0, 5, 10, 25, 50, 100, 250]) {
  const hits = candidates.filter(([a, b]) => penetration(a.box, b.box) > tol);
  const groups = new Map();
  for (const [a, b] of hits) {
    const key = [a.discipline, b.discipline].sort().join(' x ');
    groups.set(key, (groups.get(key) ?? 0) + 1);
  }
  const detail = [...groups.entries()].sort().map(([k, v]) => `${k}=${v}`).join(', ') || '-';
  console.log(`  ${String(tol).padStart(6)} mm   ${String(hits.length).padStart(7)}   ${detail}`);
}

console.log('');
const zero = candidates.filter(([a, b]) => penetration(a.box, b.box) > 0).length;
const fifty = candidates.filter(([a, b]) => penetration(a.box, b.box) > 50).length;
console.log(`Moving the tolerance from 0 mm to 50 mm takes the count from ${zero} to ${fifty}.`);
console.log('Nothing about the model changed. The tolerance is a policy about what counts');
console.log('as a problem, and a report that does not state it is not reproducible -- two');
console.log('teams running the same model will disagree and both will be right.');
